###########
# Usage:
#
#   docker run -it -v <project-resource-directory>:/workspace \
#                  --name <container-name> [image-name]
#
FROM	centos:centos6
MAINTAINER junhuih

RUN yum -y update
RUN yum groupinstall 'Development tools' -y
RUN yum install ncurses ncurses-devel wget tar git -y

# vim 7.4
RUN cd /usr/local/src && wget ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2
RUN cd /usr/local/src && tar -xjf vim-7.4.tar.bz2
RUN cd /usr/local/src && cd vim74 && chmod 777 -R ./configure
RUN cd /usr/local/src && cd vim74 && ./configure --prefix=/usr --with-features=huge --enable-rubyinterp --enable-pythoninterp
RUN cd /usr/local/src && cd vim74 && make && make install

# environment
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 0.10.38
ENV WORK_DIR /workspace

# npm & nodejs
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash \
    && source $NVM_DIR/nvm.sh \
    && nvm install v$NODE_VERSION \
    && nvm use v$NODE_VERSION \
    && nvm alias default v$NODE_VERSION

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules  
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH

# nodejs dependences
RUN npm install -g gulp js-beautify typescript-formatter jshint

# vim
RUN git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
ADD . /src
RUN cp /src/.vimrc ~/
RUN vim +PluginInstall +qall now

# work folder
# ADD app/ $WORK_DIR/ # can use it on production
# RUN cd $WORK_DIR && npm install

WORKDIR $WORK_DIR
# set image port
EXPOSE 22 80

# CMD npm start # can use it on production
CMD bash # use it at dev, maunually start the app

